### ISSUE TITLE
Proposed modifications to the JSON

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nimwc_plugins#2]
Add 3 fields to the JSON:
```json
"email": "juan@example.com",
"monetization": "https://liberapay.org/someuser",
"minimumVersion": "5.0.0",
```

- Optional, `"email"` and `"monetization"` can be empty string, but all Plugins must have it.
- With Mail we can have a `Talk to the Developer` button.
- With Mail we can have a Developer Avatars (via Libravatar), companies love to put their Logo in.
- Monetization can be a Donate, Subscribe or Buy link, (BTC, Liberapay, Patreon, etc) 100% up to the Plugin developer.
- Minimum NimWC Version: https://github.com/ThomasTJdev/nim_websitecreator/pull/63#issuecomment-469855846
- `"minimumVersion"` must Not be empty string, its an error.
- `"minimumVersion"` must be set to current Version by default by the Skeleton Creator, user can edit it.
- Mail is rendered always as a vanilla link, so it can be an HTTP link too (Slack, etc), but mail is recommended, 100% up to the Plugin developer.

**Success histories:**
- See VSCode Plugins have Avatars and Monetization builtin.

**Extras:**
- From https://github.com/ThomasTJdev/nim_websitecreator/pull/63 Plugin Descriptions on the JSON can be MarkDown/RST or Plain Text.

**Comment by ThomasTJdev** [comment]
Yes please ;)

1) The word "monetization" sounds a little intrusive to me, do we have another word? I'm not a native English speaker, so maybe it's just me..

2) Skeleton Creator needs to be updated, to ask the user all the questions, automatic insert current installed NimWC version (if it's a bin) and create the plugin local plugin.json file. Skeleton porc, `pluginSkeleton` should be moved to a module instead of being in `nimwc.nim`

**Comment by juancarlospaco** [comment]
I neither like `"monetization"` nor `"minimumVersion"` I would love something shorter and better,
but I can not think of something better that dont lose meaning. What do you think of:

`"minimumVersion"` :arrow_right: `"requires"` :grey_question: 
`"monetization"` :arrow_right: `"sustainability"` :grey_question: 


```json
"email": "juan@example.com",
"sustainability": "https://liberapay.org/someuser",
"requires": "5.0.0",
```

**Comment by juancarlospaco** [comment]
Going with `"requires"` and `"sustainability"` soon if theres no better alternative.
